# Generated by Django 4.0 on 2021-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Data',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
